export const typeImage: any = {
  BUG: require("../images/BUG.png"),
  DARK: require("../images/DARK.png"),
  WATER: require("../images/WATER.png"),
  DRAGON: require("../images/DRAGON.png"),
  ELECTRIC: require("../images/ELECTRIC.png"),
  FAIRY: require("../images/FAIRY.png"),
  FIGHTING: require("../images/FIGHTING.png"),
  FIRE: require("../images/FIRE.png"),
  FLYING: require("../images/FLYING.png"),
  GHOST: require("../images/GHOST.png"),
  GRASS: require("../images/GRASS.png"),
  GROUND: require("../images/GROUND.png"),
  ICE: require("../images/ICE.png"),
  NORMAL: require("../images/NORMAL.png"),
  POISON: require("../images/POISON.png"),
  PSYCHIC: require("../images/PSYCHIC.png"),
  ROCK: require("../images/ROCK.png"),
  STEEL: require("../images/STEEL.png"),
};
